### ISSUE TITLE
Clarify protocol

### ISSUE THREAD

**Issue by baterflyrity** [ThatXliner/aioudp#18]
Hi!

Can you please clarify what exactly protocol is used? 

There are several strange things related to raw UDP transport:

- connections in udp???
- some strange messages like "trash" are sent in background
- timeout in udp

**Comment by ThatXliner** [comment]
> Hi!
> 
> Can you please clarify what exactly protocol is used?
> 
> There are several strange things related to raw UDP transport:
> 
> * connections in udp???

This library only provides a very thin wrapper around [`asyncio.create_datagram_endpoint`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_datagram_endpoint)


> * some strange messages like "trash" are sent in background

Yea that was to [fix an issue](https://github.com/ThatXliner/aioudp/blob/ccfa0de28d0b10c41577cf485d040a035aa32aab/aioudp/client.py#L25) with clients trying to recieve messages immediately. When I originally added it, it didn't affect anything. Perhaps there was a regression or that this isn't the way to do it. I should probably make it configurable.


I would be happy to help if you could provide a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)


> * timeout in udp

[Does this help](https://aioudp.readthedocs.io/en/latest/faq.html#how-can-i-add-a-timeout)

**Comment by baterflyrity** [comment]
Thanks.

**Comment by baterflyrity** [comment]
Also want to notice that ConnectionReserError is thrown due to additional ICMP request in background. 
![image](https://github.com/ThatXliner/aioudp/assets/15788974/db8177c4-a837-40c0-ace5-95eee95db2a7)
